### ISSUE TITLE
Would be great to add a functional test using SQLAlchemy.

### ISSUE THREAD

**Issue by andrecp** [Pylons/pyramid-cookiecutter-alchemy#31] opened 2018-04-01 07:16 UTC
Hi! Thanks for the work in this cookiecutter :)
 
I was following along but found an issue,

https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/testing.html

Says, in the bottom, that for functional tests we should use 

```
class FunctionalTests(unittest.TestCase):
    def setUp(self):
        from myproject import main
        app = main({})
        from webtest import TestApp
        self.testapp = TestApp(app)

    def test_root(self):
        res = self.testapp.get('/', status=200)
        self.assertTrue(b'Pyramid' in res.body)
```

If we try to apply this on this cookiecutter we get an error from the main({}) part with a SQLAlchemy KeyError on `url`, following the unit test I was able to augment the cookie cutter with

```
class BaseFunctionalTest(unittest.TestCase):
    def setUp(self):
        self.config = testing.setUp(settings={
            'sqlalchemy.url': 'sqlite:///:memory:'
        })
        self.config.include('bookshare.models')
        settings = self.config.get_settings()

        from bookshare import main
        app = main(settings)

        from webtest import TestApp
        self.testapp = TestApp(app)

    def tearDown(self):
        testing.tearDown()
        transaction.abort()
```

However I still got the same error, after some google-ing and Stackoverflow I saw that it should be 

```
app = main(global_config={}, **settings)
```

Of course that I could've checked better the docstring of the functions and so on but still, for newcomers, not that obvious :)

Thanks!

**Comment by stevepiercy** [comment] 2018-04-01 09:02
Thanks for the report. This is an issue with Pyramid documentation, not cookiecutter. I've opened an issue https://github.com/Pylons/pyramid/issues/3248

FTR, there's a nice wiki tutorial that has correct tests.
https://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/tests.html

**Comment by stevepiercy** [comment] 2018-04-01 09:27
Actually, the problem is that you used the sqlalchemy cookiecutter, instead of the instructed starter cookiecutter, for this project. If you use the starter cookiecutter as instructed, there is no problem.

> Using the project `myproject` generated by the starter cookiecutter as described in [Creating a Pyramid Project](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/project.html)

Closing.

**Closed as completed by stevepiercy** 2018-04-01 09:27 UTC
